spring.application.name=Spring-Boot-Starters-Project

spring.devtools.restart.enabled=true

management.endpoints.web.exposure.include=*

management.info.env.enabled=true

info.app.name=Spring Boot Starters Project
info.app.description=O aplicatie Spring Boot foarte utila!
info.app.version=1.0.0

spring.security.user.name=pixel
spring.security.user.password=academy
